name: Community_nRF52_Arduino
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Fetch release version for arduino-cli
        run: |
          curl -sL https://api.github.com/repos/arduino/arduino-cli/releases/latest | \
          jq -r ".tag_name" > release-versions/arduino-cli-latest.txt
      - name: Fetch release version for Adafruit_nRF52_Arduino
        run: |
          curl -sL https://api.github.com/repos/adafruit/Adafruit_nRF52_Arduino/releases/latest | \
          jq -r ".tag_name" > release-versions/Adafruit_nRF52_Arduino-latest.txt
      - name: Fetch release version for Community_nRF52_Arduino
        run: |
          curl -sL https://api.github.com/repos/jpconstantineau/Community_nRF52_Arduino/releases/latest | \
          jq -r ".tag_name" > release-versions/Community_nRF52_Arduino-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Pierre Constantineau'
          git config --global user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version - Community_nRF52_Arduino"
          git push